version:      "3.7"

services:
  app:
    image:    webapp
    build:    .
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app
    command:  python -m flask run --host 0.0.0.0
